### ISSUE TITLE
结合语音加强复习

### ISSUE THREAD

**Issue by dongrentianyu** [oflg/TiddlyMemo#22]
我刚发现林一二做了一个可以本地化使用的离线的语音插件，输入对应文本然后点击就可以自动读出。speech-synthesis。

https://github.com/tiddly-gittly/speech-synthesis

https://tiddly-gittly.github.io/speech-synthesis/#Index:Index

然后我自己做了一个按钮，可以读标题内容。

```
<$button>
  {{$:/core/images/erase}}
  <$speech-synthesis text={{!!title}} />
</$button>
```

里面的图标是从图库里随便拿的一个。加上`$:/tags/ViewToolbar`标签就可以使用了。

我想的是可以用来实现英文语音复习。比如读单词，或者读句子，然后我们听写复习这样的复习模式。

所以应该是和问答题选择题同等级的语音题。也就是可以说出语音的语音题。

通过字段内容判断是什么题型，然后如果是语音题，就会出现一个按钮，放在toolbar上，点击读出语音。然后再点击显示标题或者caption内容，也就是卡片的正面，再点击text部分就展示正文了。大概是这样一个流程。

目前我测试了一些主流的语言大部分都是可以读的。就是日语，韩语，俄语读不出来。不知道为什么，回头我去那边提个issue好了。法语，德语，西班牙语，意大利语，葡萄牙语都是可以读的。就是感觉读起来很生硬。

下次更新的话，我感觉可以把这个功能也加进去。或者独立成一个子插件。因为这个插件要附带上面speech-synthesis插件。做成子插件比较好的样子。因为有些人可能用不到这个功能。

**Comment by oflg** [comment]
可以做个插件，不过我没精力做。

**Comment by dongrentianyu** [comment]
[https://tw-cn.netlify.app/#%E5%A6%82%E4%BD%95%E5%88%B6%E4%BD%9C%E8%AF%AD%E9%9F%B3%E9%A2%98%EF%BC%9F](url)

写了教程，我就先关了issue。

**Comment by dongrentianyu** [comment]
本来我是想过去设计一个模板的，但我发现好难设计。因为有的人可能只需要读填空的内容，有的可能会想读整个全文内容。而且这个还要和具体的题目结合起来。我觉得或许可以采用另一种设计思路。分两种，一种是填空题，通过语音来帮助提示背单词。而其他要读的内容，则可以存放在一个状态条目里。也就是把复制的内容放在状态条目里，点击然后发出语音。但这样好像也很难操作的样子。唉，还是等需求上来了再思考吧。
