### ISSUE TITLE
钓鱼子插件，摸鱼插件无法正常工作

### ISSUE THREAD

**Issue by Unword** [oflg/TiddlyMemo#26]
在墨屉手册中，摸鱼插件正常工作。
但是下载下来的墨屉，就不能通过选中生成摘录。
是最新版本的墨屉。
不大确定是不是Dynannotate的原因，5.2.5、5.2.7、5.3.0都试过，

**Comment by oflg** [comment]
已经在这里解答：https://github.com/oflg/fishing-catchfish/issues/12
